# Operator Service - dev profile
spring.datasource.url=jdbc:postgresql://10.10.22.91:5432/b2b_platform?currentSchema=b2b
spring.datasource.username=postgres
spring.datasource.password=Redim04$

redis.host=0.0.0.0
spring.data.redis.host=0.0.0.0
redis.port=6379
spring.data.redis.port=6379
