package com.b2bplatform.wallet.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * Pending Fund Transfer Transaction entity
 * Used for two-step flow: Request → Confirm
 * 
 * Flow:
 * 1. Step 1: Create pending transaction (status: PENDING)
 * 2. Step 2: Confirm pending transaction (status: CONFIRMED)
 * 3. Auto-expire: Old pending transactions expire (status: EXPIRED)
 */
@Entity
@Table(name = "pending_fund_transactions", indexes = {
    @Index(name = "idx_pending_operator_player", columnList = "operator_id,player_id"),
    @Index(name = "idx_pending_status", columnList = "status"),
    @Index(name = "idx_pending_expires", columnList = "expires_at"),
    @Index(name = "idx_pending_payment_id", columnList = "payment_id"),
    @Index(name = "idx_pending_created_at", columnList = "created_at")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PendingFundTransaction {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Unique payment identifier (generated by B2B platform)
     */
    @Column(name = "payment_id", unique = true, nullable = false, length = 100)
    private String paymentId;
    
    /**
     * Operator ID (internal reference)
     */
    @Column(name = "operator_id", nullable = false)
    private Long operatorId;
    
    /**
     * Player identifier
     */
    @Column(name = "player_id", nullable = false, length = 100)
    private String playerId;
    
    /**
     * Transaction amount
     */
    @Column(name = "amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;
    
    /**
     * Currency code
     */
    @Column(name = "currency", nullable = false, length = 10)
    private String currency;
    
    /**
     * Unit type (CENTS or DECIMAL)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "unit_type", nullable = false, length = 10)
    private UnitType unitType;
    
    /**
     * Transaction type (deposit or withdrawal)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 20)
    private FundTransferType transactionType;
    
    /**
     * Status of pending transaction
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private PendingStatus status = PendingStatus.PENDING;
    
    /**
     * Expiration timestamp (default: 15 minutes from creation)
     */
    @Column(name = "expires_at")
    private LocalDateTime expiresAt;
    
    /**
     * Creation timestamp
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    /**
     * Confirmation timestamp
     */
    @Column(name = "confirmed_at")
    private LocalDateTime confirmedAt;
    
    /**
     * Who confirmed the transaction
     */
    @Column(name = "confirmed_by", length = 100)
    private String confirmedBy;
    
    /**
     * Operator response (JSONB)
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "operator_response", columnDefinition = "jsonb")
    private Map<String, Object> operatorResponse;
    
    /**
     * Created by (audit field)
     */
    @Column(name = "created_by", length = 100)
    private String createdBy;
    
    /**
     * Updated timestamp
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    /**
     * Updated by (audit field)
     */
    @Column(name = "updated_by", length = 100)
    private String updatedBy;
    
    /**
     * Fund Transfer Type
     */
    public enum FundTransferType {
        DEPOSIT,      // Player deposits funds from operator
        WITHDRAWAL    // Player withdraws funds to operator
    }
    
    /**
     * Pending Transaction Status
     */
    public enum PendingStatus {
        PENDING,      // Transaction created, waiting for confirmation
        CONFIRMED,    // Transaction confirmed and processed
        EXPIRED,      // Transaction expired (not confirmed in time)
        CANCELLED     // Transaction cancelled
    }
    
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (createdAt == null) {
            createdAt = now;
        }
        if (updatedAt == null) {
            updatedAt = now;
        }
        if (paymentId == null || paymentId.isEmpty()) {
            paymentId = generatePaymentId();
        }
        if (expiresAt == null) {
            // Default expiration: 15 minutes from creation
            expiresAt = now.plusMinutes(15);
        }
    }
    
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
        if (status == PendingStatus.CONFIRMED && confirmedAt == null) {
            confirmedAt = LocalDateTime.now();
        }
    }
    
    /**
     * Check if transaction is expired
     */
    public boolean isExpired() {
        return expiresAt != null && LocalDateTime.now().isAfter(expiresAt) 
            && status == PendingStatus.PENDING;
    }
    
    /**
     * Check if transaction can be confirmed
     */
    public boolean canBeConfirmed() {
        return status == PendingStatus.PENDING && !isExpired();
    }
    
    private String generatePaymentId() {
        return "PMT_" + UUID.randomUUID().toString().replace("-", "").substring(0, 16).toUpperCase();
    }
}
